version: "2.3"

services:

  people_counter:
    container_name: people_counter
    build: .
    environment:
      - DISPLAY
      - FLASK_APP=server  # needed for flask run
      - FLASK_ENV=development  # activate flask debug mode
    ipc: host # for GUI
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # for GUI access
      - .:/peoplecounter
    ports:
      - "5000:5000"
